name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6
      - name: Prepare environment
        run: |
          poetry add -D pytest-github-actions-annotate-failures
          poetry install
      - name: Run tests
        run: |
          poetry run pytest
